# -*- coding: utf-8 -*-
"""
Django settings for myerp project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-w36p!(@@q9+7ko8v%g2cc$sz+9a1_g1ocj=)uo2=sy)17vzztx'

DEBUG = True

ALLOWED_HOSTS = ['talhacelik.com', 'dormoni.talhacelik.com', '127.0.0.1', '']

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'toexport.apps.ToexportConfig',
	'authentication.apps.AuthenticationConfig',
	'main.apps.MainConfig',
	'parameters.apps.ParametersConfig',
	'people.apps.PeopleConfig',
	'schema.apps.SchemaConfig',
	'rest_framework',
	'rest_framework.authtoken',
	'django_filters'
]
 
MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'functions.Logger.LoggerMiddleware'
]

ROOT_URLCONF = 'myerp.urls'

TEMPLATES = [
				{
					'BACKEND':'django.template.backends.django.DjangoTemplates',
  					'DIRS':[BASE_DIR / 'templates'],
					'APP_DIRS':True,
					'OPTIONS':{'context_processors':[
						'django.template.context_processors.debug',
						'django.template.context_processors.request',
						'django.contrib.auth.context_processors.auth',
						'django.contrib.messages.context_processors.messages'],
						'libraries':{'TemplateFuncs': 'functions.TemplateFuncs'}
					}
				}
			]

WSGI_APPLICATION = 'dormoni.wsgi.application'

DATABASES = {
				'default':{
							'ENGINE':'django.db.backends.sqlite3',
  							'NAME':BASE_DIR / 'data_db.sqlite3'
						},
 				'schema':{
					 		'ENGINE':'django.db.backends.sqlite3',
  							'NAME':BASE_DIR / 'schema_db.sqlite3'
						}
			}

AUTH_PASSWORD_VALIDATORS = [
								{'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
								{'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
								{'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
								{'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'}
							]

REST_FRAMEWORK = {
					'DEFAULT_FILTER_BACKENDS':['django_filters.rest_framework.DjangoFilterBackend'],
 					'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.LimitOffsetPagination'
				}


# LOCALICATION INFO
LANGUAGE_CODE = 'tr-tr'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = False
USE_TZ = True

# STATIC INFO
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'templates/source')]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# DEFAULT INFO
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REGISTRATION INFO
LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'home'
LOGOUT_URL = 'logout'

# MAIL INFO
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'myerp.talhacelik.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'admin@myerp.talhacelik.com'
EMAIL_HOST_PASSWORD = 'Hobula.5357'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_USER_SSL = True
EMAIL_USER_TLS = True

# # LOGGING INFO
# import datetime
# LOGGING = {'version':1,
#  'disable_existing_loggers':False,
#  'formatters':{'verbose':{'format': 'levelname:%(levelname)s_asctime:%(asctime)s_created:%(created)f_filename:%(filename)s_funcName:%(funcName)s_levelno:%(levelno)s_lineno:%(lineno)d_module:%(module)s_msecs:%(msecs)d_message:%(message)s_name:%(name)s_pathname:%(pathname)s_process:%(process)d_processName:%(processName)s_relativeCreated:%(relativeCreated)d_thread:%(thread)d_threadName:%(threadName)s_'},
#   'simple':{'format': '%(levelname)s %(message)s'}},
#  'handlers':{'console':{'level':'INFO',
#    'class':'logging.StreamHandler',
#    'formatter':'simple'},
#   'file':{'level':'INFO',
#    'class':'logging.FileHandler',
#    'filename':os.getcwd() + '/logger/logger_%s.log' % datetime.datetime.now().strftime('%Y-%m-%d'),
#    'formatter':'simple'}},
#  'loggers':{'django': {'handlers':[
# 			  'console'],
# 			 'level':'INFO',
# 			 'propagate':False}}}