# Generated by Django 3.2.5 on 2021-09-12 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Bölüm',
                'db_table': 'main_department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Rehber Grubu',
                'db_table': 'main_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskSchedulerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
                ('period_amount', models.CharField(blank=True, max_length=10, null=True, verbose_name='Period Miktarı')),
                ('run_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Çalıştırma Zamanı')),
                ('run_func', models.CharField(blank=True, max_length=200, null=True, verbose_name='Çalıştırılacak Fonksiyon')),
                ('is_active', models.BooleanField(blank=True, default=0, null=True, verbose_name='Aktif Mi?')),
                ('period_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.periodmodel', verbose_name='Period Sıklığı')),
            ],
            options={
                'verbose_name': 'Görev Zamanlayıcısı',
                'db_table': 'main_taskscheduler',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('city_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.citymodel', verbose_name='İli')),
                ('type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.schooltypemodel', verbose_name='Okul Tipi')),
            ],
            options={
                'verbose_name': 'Okul',
                'db_table': 'main_school',
                'ordering': ['city_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CorporationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('web_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Web Adresi')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresi')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('city_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.citymodel', verbose_name='İli')),
                ('market_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.marketmodel', verbose_name='Market Tipi')),
                ('town_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.townmodel', verbose_name='İlçesi')),
                ('type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.corporationtypemodel', verbose_name='Firma Tipi')),
            ],
            options={
                'verbose_name': 'Firma',
                'db_table': 'main_corporation',
                'ordering': ['name'],
            },
        ),
    ]
