# Generated by Django 3.2.5 on 2021-10-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20211006_2156'),
        ('main', '0004_alter_taskschedulermodel_run_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupModel',
            new_name='PeopleGroupModel',
        ),
    ]
