# Generated by Django 3.2.5 on 2021-11-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Not')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Not',
                'db_table': 'note_note',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='NoteRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_key', models.CharField(blank=True, max_length=10, null=True, verbose_name='Birincil Anahtar')),
                ('note_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='note.notemodel', verbose_name='Not')),
                ('table_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schema.tablemodel', verbose_name='Tablo')),
            ],
            options={
                'verbose_name': 'Not Kaydı',
                'db_table': 'note_noterecord',
                'ordering': [],
            },
        ),
    ]
