# -*- coding: utf-8 -*-
from django.contrib import admin
from .models import ContinentModel, CountryModel, CityModel, TownModel, CardTypeModel, ChangePurposeModel, RepetitiveTypeModel, CorporationTypeModel, MarketModel, EmailTypeModel, EventTypeModel, GenderModel, MediaTypeModel, PeriodModel, PhoneTypeModel, RelationTypeModel, SchoolTypeModel, SeriesDownloadModel, GenreModel, SeriesStateModel, SeriesTypeModel, FinancialCategoryModel, TransactionTypeModel, OperationTypeModel, AppTypeModel, PathTypeModel, ClothesTypeModel, CarClassModel, CarTypeModel, CarFuelTypeModel, CarUsageModel, FunctionTypeModel
admin.site.register(ContinentModel)
admin.site.register(CountryModel)
admin.site.register(CityModel)
admin.site.register(TownModel)
admin.site.register(CardTypeModel)
admin.site.register(ChangePurposeModel)
admin.site.register(RepetitiveTypeModel)
admin.site.register(CorporationTypeModel)
admin.site.register(MarketModel)
admin.site.register(EmailTypeModel)
admin.site.register(EventTypeModel)
admin.site.register(GenderModel)
admin.site.register(MediaTypeModel)
admin.site.register(PeriodModel)
admin.site.register(PhoneTypeModel)
admin.site.register(RelationTypeModel)
admin.site.register(SchoolTypeModel)
admin.site.register(SeriesDownloadModel)
admin.site.register(GenreModel)
admin.site.register(SeriesStateModel)
admin.site.register(SeriesTypeModel)
admin.site.register(FinancialCategoryModel)
admin.site.register(TransactionTypeModel)
admin.site.register(OperationTypeModel)
admin.site.register(AppTypeModel)
admin.site.register(PathTypeModel)
admin.site.register(ClothesTypeModel)
admin.site.register(CarClassModel)
admin.site.register(CarTypeModel)
admin.site.register(CarFuelTypeModel)
admin.site.register(CarUsageModel)
admin.site.register(FunctionTypeModel)