# Generated by Django 3.2.5 on 2022-01-22 08:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_status', models.CharField(max_length=20, verbose_name='Durumu')),
                ('registration_number', models.CharField(max_length=20, verbose_name='Sicil No')),
                ('chamber_registraion_sytem_no', models.CharField(max_length=20, verbose_name='Oda Sicil No')),
                ('company_title', models.CharField(max_length=100, verbose_name='Firma Ünvanı')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('second_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='İkincil Adı')),
                ('business_address', models.CharField(max_length=200, verbose_name='İş Adresi')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon No')),
                ('fax_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax No')),
                ('hyperlink', models.CharField(max_length=500, verbose_name='Web Sayfası')),
                ('date_of_registration', models.DateField(default=datetime.date.today, verbose_name='Odaya Kayıt Tarihi')),
                ('capital', models.CharField(max_length=500, verbose_name='Sermaye')),
                ('occupational_group', models.CharField(max_length=500, verbose_name='Meslek Grubu')),
                ('nace_codes', models.CharField(max_length=500, verbose_name='Nace Kodları')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Firma',
                'db_table': 'authentication_company',
                'ordering': ['company_title'],
            },
        ),
        migrations.CreateModel(
            name='BranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kodu')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.companymodel', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Firma Şubesi',
                'db_table': 'authentication_branch',
                'ordering': ['company_id', 'name'],
                'unique_together': {('company_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AuthenticationUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.CharField(blank=True, max_length=200, null=True, verbose_name='Profil Fotoğrafı')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
                ('company_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.companymodel', verbose_name='Firma')),
                ('user_id', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'db_table': 'authentication_authenticationuser',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='AuthenticationGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kodu')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
                ('branch_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='authentication.branchmodel', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Grup',
                'db_table': 'authentication_authentacationgroup',
                'ordering': ['branch_id', 'name'],
                'unique_together': {('branch_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
                ('company_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.companymodel', verbose_name='Firma')),
                ('group_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='authentication.authenticationgroupmodel', verbose_name='Grup')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='authentication.authenticationusermodel', verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Grupları',
                'db_table': 'authentication_usergroup',
                'ordering': ['group_id', 'user_id'],
                'unique_together': {('user_id', 'group_id')},
            },
        ),
    ]
