# Generated by Django 3.2.5 on 2021-09-12 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schema', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parameters', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True, verbose_name='IP Adres')),
                ('is_active', models.BooleanField(blank=True, default=0, null=True, verbose_name='Aktif Mi?')),
                ('auth_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='Yetki Anahtarı')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sahibi')),
            ],
            options={
                'verbose_name': 'Kullanıcı Ipsi',
                'db_table': 'authentication_userıp',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='OperationHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_key', models.CharField(blank=True, max_length=10, null=True, verbose_name='Birincil Anahtar')),
                ('detail', models.CharField(blank=True, max_length=200, null=True, verbose_name='Detay')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Zamanı')),
                ('app_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schema.appmodel', verbose_name='Uygulama')),
                ('type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.operationtypemodel', verbose_name='Türü')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sahibi')),
            ],
            options={
                'verbose_name': 'İşlem Geçmişi',
                'db_table': 'authentication_operationhistory',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='HistoryLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Tarih')),
                ('time', models.TimeField(auto_now_add=True, null=True, verbose_name='Saat')),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True, verbose_name='IP Adres')),
                ('primary_key', models.CharField(blank=True, max_length=10, null=True, verbose_name='Birincil Anahtar')),
                ('action', models.CharField(blank=True, max_length=100, null=True, verbose_name='Eylem')),
                ('web_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Web Adresi')),
                ('session', models.CharField(blank=True, max_length=200, null=True, verbose_name='Oturum')),
                ('csrf_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kontrol Anahtarı')),
                ('app_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schema.appmodel', verbose_name='Uygulama')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Geçmiş Kayıt',
                'db_table': 'authentication_historylog',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
