# Generated by Django 3.2.5 on 2022-01-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationgroupmodel',
            name='branch_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='group_info', to='authentication.branchmodel', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='authenticationusermodel',
            name='company_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='authentication.companymodel', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='branchmodel',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_info', to='authentication.companymodel', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='usergroupmodel',
            name='company_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usergroup_info', to='authentication.companymodel', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='usergroupmodel',
            name='group_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='usergroup_info', to='authentication.authenticationgroupmodel', verbose_name='Grup'),
        ),
        migrations.AlterField(
            model_name='usergroupmodel',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='usergroup_info', to='authentication.authenticationusermodel', verbose_name='Kullanıcı'),
        ),
    ]
