# Generated by Django 3.1.4 on 2022-02-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220225_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationgroupmodel',
            name='company_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_info', to='authentication.companymodel', verbose_name='Firma'),
        ),
    ]
