# Generated by Django 3.2.5 on 2021-09-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210919_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historylogmodel',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adres'),
        ),
    ]
