# Generated by Django 3.1.4 on 2022-02-25 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
        ('authentication', '0004_authenticationgroupmodel_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationgroupmodel',
            name='company_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_info', to='authentication.companymodel', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='authenticationusermodel',
            name='branch_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_info', to='authentication.branchmodel', verbose_name='Şube'),
        ),
        migrations.AlterField(
            model_name='authenticationusermodel',
            name='company_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_info', to='authentication.companymodel', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='usergroupmodel',
            name='company_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usergroup_info', to='authentication.companymodel', verbose_name='Firma'),
        ),
        migrations.CreateModel(
            name='GroupPathModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
                ('company_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userpath_info', to='authentication.companymodel', verbose_name='Firma')),
                ('group_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='userpath_info', to='authentication.authenticationgroupmodel', verbose_name='Grup')),
                ('path_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='userpath_info', to='schema.pathmodel', verbose_name='Güzergah')),
            ],
            options={
                'verbose_name': 'Kullanıcı Grupları',
                'db_table': 'authentication_grouppath',
                'ordering': ['path_id', 'group_id'],
                'unique_together': {('group_id', 'path_id')},
            },
        ),
    ]
