# Generated by Django 3.2.5 on 2021-09-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_useripmodel_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useripmodel',
            name='permission',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='İzin Durumu'),
        ),
        migrations.AlterField(
            model_name='useripmodel',
            name='is_active',
            field=models.BooleanField(blank=True, default=1, null=True, verbose_name='Aktiflik'),
        ),
    ]
