# Generated by Django 3.2.5 on 2021-09-19 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0002_alter_tablemodel_app_id'),
        ('authentication', '0007_auto_20210919_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationhistorymodel',
            name='app_id',
        ),
        migrations.AddField(
            model_name='operationhistorymodel',
            name='table_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schema.tablemodel', verbose_name='Tablo'),
        ),
    ]
