# Generated by Django 3.2.5 on 2021-09-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20210919_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='useripmodel',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aktivasyon Zamanı'),
        ),
        migrations.AlterField(
            model_name='historylogmodel',
            name='action',
            field=models.CharField(max_length=50, null=True, verbose_name='Eylem'),
        ),
        migrations.AlterField(
            model_name='historylogmodel',
            name='hyperlink',
            field=models.CharField(max_length=200, null=True, verbose_name='Bağlantı Adresi'),
        ),
        migrations.AlterField(
            model_name='historylogmodel',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, verbose_name='IP Adres'),
        ),
        migrations.AlterField(
            model_name='historylogmodel',
            name='session',
            field=models.CharField(max_length=200, null=True, verbose_name='Oturum'),
        ),
        migrations.AlterField(
            model_name='useripmodel',
            name='auth_key',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Yetki Anahtarı'),
        ),
        migrations.AlterField(
            model_name='useripmodel',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, unique=True, verbose_name='IP Adres'),
        ),
    ]
