# Generated by Django 3.2.5 on 2021-10-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210929_0008'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useripmodel',
            table='authentication_userip',
        ),
    ]
