# Generated by Django 3.2.5 on 2022-01-22 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kodu')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tam Adı')),
                ('id_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Kimlik Numarası')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='İlk Adı')),
                ('second_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='İkinci Adı')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ek Adı')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Soyadı')),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Takma Adı')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ünvanı')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('hometown', models.CharField(blank=True, max_length=50, null=True, verbose_name='Memleketi')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresi')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Ölüm Tarihi')),
                ('favorite', models.BooleanField(blank=True, default=0, null=True, verbose_name='Favori')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
                ('branch_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.branchmodel', verbose_name='Şube')),
                ('city_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.citymodel', verbose_name='İli')),
                ('company_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.companymodel', verbose_name='Firma')),
                ('country_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.countrymodel', verbose_name='Ülkesi')),
                ('gender_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.gendermodel', verbose_name='Cinsiyeti')),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.peoplegroupmodel', verbose_name='Grubu')),
            ],
            options={
                'verbose_name': 'Rehber',
                'db_table': 'people_person',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kullanıcı Adı')),
                ('hyperlink', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bağlantı Adresi')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
                ('branch_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.branchmodel', verbose_name='Şube')),
                ('company_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.companymodel', verbose_name='Firma')),
                ('media_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.mediatypemodel', verbose_name='Sosyal Medya Tipi')),
                ('person_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.personmodel', verbose_name='Kimin')),
            ],
            options={
                'verbose_name': 'Sosyal Medya Hesabı',
                'db_table': 'people_socialmedia',
                'ordering': ['person_id'],
            },
        ),
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('hyperlink', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bağlantı Adresi')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
                ('branch_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.branchmodel', verbose_name='Şube')),
                ('company_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.companymodel', verbose_name='Firma')),
                ('person_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.personmodel', verbose_name='Kimin')),
            ],
            options={
                'verbose_name': 'Kişi Fotoğrafı',
                'db_table': 'people_photo',
                'ordering': ['person_id'],
            },
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
                ('branch_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.branchmodel', verbose_name='Şube')),
                ('company_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.companymodel', verbose_name='Firma')),
                ('person_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.personmodel', verbose_name='Kimin')),
                ('phone_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.phonetypemodel', verbose_name='Telefon Tipi')),
            ],
            options={
                'verbose_name': 'Telefonu Numarası',
                'db_table': 'people_phone',
                'ordering': ['person_id'],
            },
        ),
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-Mail Adresi')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
                ('branch_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.branchmodel', verbose_name='Şube')),
                ('company_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.companymodel', verbose_name='Firma')),
                ('email_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.emailtypemodel', verbose_name='E-Mail Tipi')),
                ('person_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.personmodel', verbose_name='Kimin')),
            ],
            options={
                'verbose_name': 'Kişi E-Posta Adresi',
                'db_table': 'people_email',
                'ordering': ['person_id'],
            },
        ),
    ]
