# Generated by Django 3.2.5 on 2021-09-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomodel',
            name='web_address',
        ),
        migrations.RemoveField(
            model_name='socialmediamodel',
            name='web_address',
        ),
        migrations.AddField(
            model_name='photomodel',
            name='hyperlink',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bağlantı Adresi'),
        ),
        migrations.AddField(
            model_name='socialmediamodel',
            name='hyperlink',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bağlantı Adresi'),
        ),
    ]
