# Generated by Django 3.2.5 on 2022-01-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220122_1240'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='branch_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_info', to='authentication.branchmodel', verbose_name='Şube'),
        ),
        migrations.AlterField(
            model_name='emailmodel',
            name='company_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_info', to='authentication.companymodel', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='emailmodel',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_info', to='people.personmodel', verbose_name='Kimin'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='branch_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_info', to='authentication.branchmodel', verbose_name='Şube'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='company_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_info', to='authentication.companymodel', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='branch_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_info', to='authentication.branchmodel', verbose_name='Şube'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='company_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_info', to='authentication.companymodel', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_info', to='people.personmodel', verbose_name='Kimin'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='branch_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_info', to='authentication.branchmodel', verbose_name='Şube'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='company_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_info', to='authentication.companymodel', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_info', to='people.personmodel', verbose_name='Kimin'),
        ),
        migrations.AlterField(
            model_name='socialmediamodel',
            name='branch_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_info', to='authentication.branchmodel', verbose_name='Şube'),
        ),
        migrations.AlterField(
            model_name='socialmediamodel',
            name='company_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_info', to='authentication.companymodel', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='socialmediamodel',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_info', to='people.personmodel', verbose_name='Kimin'),
        ),
    ]
