# Generated by Django 3.2.5 on 2021-10-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20210919_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Ölüm Tarihi'),
        ),
    ]
