# Generated by Django 3.1.4 on 2022-02-25 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PathModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Başlık')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='Güzergah')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kodu')),
                ('type_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Güzergah Tipi')),
                ('action', models.CharField(blank=True, max_length=100, null=True, verbose_name='Eylemi')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Güzergah',
                'db_table': 'schema_path',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParentPathModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_level', models.CharField(blank=True, max_length=100, null=True, verbose_name='Menü Seviyesi')),
                ('order', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sıra No')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklama')),
                ('path_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='parentpath_info', to='schema.pathmodel', verbose_name='Güzergah')),
            ],
            options={
                'verbose_name': 'Üst Menü Güzergah',
                'db_table': 'schema_parentpath',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChildPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_level', models.CharField(blank=True, max_length=100, null=True, verbose_name='Menü Seviyesi')),
                ('order', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sıra No')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklama')),
                ('parentpath_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='childpath_info', to='schema.parentpathmodel', verbose_name='Güzergah')),
                ('path_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='childpath_info', to='schema.pathmodel', verbose_name='Güzergah')),
            ],
            options={
                'verbose_name': 'Alt Menü Güzergah',
                'db_table': 'schema_childpath',
                'ordering': ['order', 'parentpath_id'],
            },
        ),
    ]
