# Generated by Django 3.2.5 on 2021-09-12 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('verbose_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Başlık')),
                ('type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.apptypemodel', verbose_name='Uygulama Türü')),
            ],
            options={
                'verbose_name': 'Uygulama',
                'db_table': 'schema_app',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('db_table', models.CharField(blank=True, max_length=50, null=True, verbose_name='Veritabanı Tablo Adı')),
                ('verbose_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Başlık')),
                ('list_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Liste Başlığı')),
                ('form_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Form Başlığı')),
                ('detail_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Detay Başlığı')),
                ('ordering', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sıralama')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Sıra No')),
                ('verbose_name_plural', models.CharField(blank=True, max_length=100, null=True, verbose_name='Çoğul Başlık')),
                ('app_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schema.appmodel', verbose_name='Uygulama')),
            ],
            options={
                'verbose_name': 'Tablo',
                'db_table': 'schema_table',
                'ordering': ['app_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PathModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Başlık')),
                ('path', models.CharField(blank=True, max_length=100, null=True, verbose_name='Güzergah')),
                ('view_func', models.CharField(blank=True, max_length=100, null=True, verbose_name='View Fonksiyonu')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Konumu')),
                ('app_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schema.appmodel', verbose_name='Uygulama')),
                ('type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.pathtypemodel', verbose_name='Güzergah Tipi')),
            ],
            options={
                'verbose_name': 'Güzergah Listesi',
                'db_table': 'schema_path',
                'ordering': ['app_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FunctionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dosya Adı')),
                ('parent', models.CharField(blank=True, max_length=10, null=True, verbose_name='Üst Fonskiyon')),
                ('order', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sırası')),
                ('data_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Veri Konumu')),
                ('app_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schema.appmodel', verbose_name='Uygulama')),
                ('type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.functiontypemodel', verbose_name='Fonksiyon Türü')),
            ],
            options={
                'verbose_name': 'Fonksiyon',
                'db_table': 'schema_function',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='FieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('verbose_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Başlık')),
                ('field', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alan Türü')),
                ('null', models.BooleanField(blank=True, default=True, null=True, verbose_name='Null ?')),
                ('blank', models.BooleanField(blank=True, default=True, null=True, verbose_name='Blank ?')),
                ('max_length', models.CharField(blank=True, max_length=5, null=True, verbose_name='En Fazla Uzunluk')),
                ('on_delete', models.CharField(blank=True, default=django.db.models.deletion.SET_NULL, max_length=100, null=True, verbose_name='Silinme Şekli')),
                ('to', models.CharField(blank=True, max_length=50, null=True, verbose_name='İlişkili Tablo')),
                ('default', models.CharField(blank=True, max_length=100, null=True, verbose_name='Varsayılan Değer')),
                ('max_digits', models.CharField(blank=True, max_length=5, null=True, verbose_name='En Fazla Hane')),
                ('decimal_places', models.CharField(blank=True, max_length=5, null=True, verbose_name='Virgülden Sonraki Hane')),
                ('is_generated', models.BooleanField(blank=True, default=0, null=True, verbose_name='Oluşturulan')),
                ('show_list', models.BooleanField(blank=True, default=True, null=True, verbose_name='Listede Gösterimi')),
                ('form_create', models.BooleanField(blank=True, default=True, null=True, verbose_name='Oluşturulabilir')),
                ('show_detail', models.BooleanField(blank=True, default=True, null=True, verbose_name='Detayda Gösterimi')),
                ('form_update', models.BooleanField(blank=True, default=True, null=True, verbose_name='Değiştirilebilir')),
                ('form_delete', models.BooleanField(blank=True, default=True, null=True, verbose_name='Silinebilir')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Sıra No')),
                ('help_text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Yardımcı Metin')),
                ('error_messages', models.CharField(blank=True, max_length=500, null=True, verbose_name='Hata Mesajları')),
                ('auto_now', models.CharField(blank=True, default=True, max_length=5, null=True, verbose_name='Otomatik Zaman Ekle')),
                ('auto_now_add', models.CharField(blank=True, default=True, max_length=5, null=True, verbose_name='Otomatik Zamanı Düzenle')),
                ('table_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schema.tablemodel', verbose_name='Model Adı')),
            ],
            options={
                'verbose_name': 'Model Alanı',
                'db_table': 'schema_field',
                'ordering': ['table_id', 'order'],
            },
        ),
    ]
