# Generated by Django 3.2.5 on 2021-09-12 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemodel',
            name='app_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_list', to='schema.appmodel', verbose_name='Uygulama'),
        ),
    ]
