# Generated by Django 3.1.4 on 2022-02-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0002_auto_20220226_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodel',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Etiket'),
        ),
    ]
