# Generated by Django 3.2.5 on 2021-10-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0002_alter_tablemodel_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathmodel',
            name='icon_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sidebar İcon Kodu'),
        ),
    ]
