# Generated by Django 3.2.5 on 2021-10-02 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0003_pathmodel_icon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemodel',
            name='app_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schema.appmodel', verbose_name='Uygulama'),
        ),
    ]
