# Generated by Django 3.2.5 on 2022-03-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0005_auto_20220313_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarmodel',
            name='menu_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Menü Kodu'),
        ),
        migrations.AlterField(
            model_name='sidebarmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı'),
        ),
    ]
