# Generated by Django 3.2.5 on 2021-10-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0005_auto_20211009_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodel',
            name='sidebar_icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İcon'),
        ),
        migrations.AddField(
            model_name='tablemodel',
            name='sidebar_icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İcon'),
        ),
    ]
