# Generated by Django 3.2.5 on 2021-11-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0006_auto_20211024_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldmodel',
            name='form_create',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Oluşturulabilir'),
        ),
        migrations.AlterField(
            model_name='fieldmodel',
            name='form_update',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Değiştirilebilir'),
        ),
        migrations.AlterField(
            model_name='fieldmodel',
            name='is_generated',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Oluşturulan'),
        ),
        migrations.AlterField(
            model_name='fieldmodel',
            name='show_detail',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Detayda Gösterimi'),
        ),
        migrations.AlterField(
            model_name='fieldmodel',
            name='show_list',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Listede Gösterimi'),
        ),
    ]
