# Generated by Django 3.2.5 on 2022-01-22 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContinentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Kıta',
                'db_table': 'parameters_continent',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'E-Mail Türü',
                'db_table': 'parameters_emailtype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Cinsiyet',
                'db_table': 'parameters_gender',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('base_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kaynak Url')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Sosyal Medya Türü',
                'db_table': 'parameters_mediatype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PeopleGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Rehber Grubu',
                'db_table': 'parameters_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhoneTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Telefon Türü',
                'db_table': 'parameters_phonetype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kodu')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
                ('continent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.continentmodel', verbose_name='Kıtası')),
            ],
            options={
                'verbose_name': 'Ülke',
                'db_table': 'parameters_country',
                'ordering': ['continent_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kodu')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
                ('country_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.countrymodel', verbose_name='Ülkesi')),
            ],
            options={
                'verbose_name': 'Şehir',
                'db_table': 'parameters_city',
                'ordering': ['country_id', 'name'],
            },
        ),
    ]
