# Generated by Django 3.2.5 on 2021-09-12 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Uygulama Tipi',
                'db_table': 'parameters_apptype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Araba Sınıfı',
                'db_table': 'parameters_carclass',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CardTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Kart Türü Listesi',
                'db_table': 'parameters_cardtype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarFuelTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Yakıt Tipi',
                'db_table': 'parameters_carfueltype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Cinsi',
                'db_table': 'parameters_cartype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarUsageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Kullanım Amacı',
                'db_table': 'parameters_carusage',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChangePurposeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Aldım - Verdim Amacı',
                'db_table': 'parameters_changepurpose',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Şehir',
                'db_table': 'parameters_city',
                'ordering': ['country_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClothesTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Kıyafet Tipi',
                'db_table': 'parameters_clothestype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContinentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Kıta',
                'db_table': 'parameters_continent',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CorporationTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Firma Türü',
                'db_table': 'parameters_corporationtype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'E-Mail Türü',
                'db_table': 'parameters_emailtype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Etkinlik Türü',
                'db_table': 'parameters_eventtype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Finans Kategorisi',
                'db_table': 'parameters_financialcategory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FunctionTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Fonksiyon Tipi',
                'db_table': 'parameters_functiontype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Cinsiyet',
                'db_table': 'parameters_gender',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Seri Tarzı',
                'db_table': 'parameters_genre',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Firma Sektörü',
                'db_table': 'parameters_market',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('base_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kaynak Url')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Sosyal Medya Türü',
                'db_table': 'parameters_mediatype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OperationTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'İşlem Türü',
                'db_table': 'parameters_operationtype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PathTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Güzergah Tipi',
                'db_table': 'parameters_pathtype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PeriodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('day', models.CharField(blank=True, max_length=4, null=True, verbose_name='Gün')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Dönem',
                'db_table': 'parameters_period',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhoneTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Telefon Türü',
                'db_table': 'parameters_phonetype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RelationTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Kişi İlişkisi',
                'db_table': 'parameters_relationship',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RepetitiveTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Tekrarlı Olay Türü',
                'db_table': 'parameters_repetitivetype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Okul Türü',
                'db_table': 'parameters_schooltype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeriesDownloadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Seri İndirilebilirliği',
                'db_table': 'parameters_download',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeriesStateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Takip Durumu',
                'db_table': 'parameters_seriesstate',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeriesTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Seri Türü',
                'db_table': 'parameters_seriestype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
            ],
            options={
                'verbose_name': 'Muhasebe Türü',
                'db_table': 'parameters_transactiontype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TownModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kodu')),
                ('city_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.citymodel', verbose_name='İli')),
            ],
            options={
                'verbose_name': 'İlçe Listesi',
                'db_table': 'parameters_town',
                'ordering': ['city_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kodu')),
                ('continent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.continentmodel', verbose_name='Kıtası')),
            ],
            options={
                'verbose_name': 'Ülke',
                'db_table': 'parameters_country',
                'ordering': ['continent_id', 'name'],
            },
        ),
        migrations.AddField(
            model_name='citymodel',
            name='country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.countrymodel', verbose_name='Ülkesi'),
        ),
    ]
