# Generated by Django 3.2.5 on 2021-10-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathtypemodel',
            name='icon_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sidebar İcon Kodu'),
        ),
    ]
