# uncompyle6 version 3.8.0
# Python bytecode 3.8.0 (3413)
# Decompiled from: Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
# Embedded file name: C:\Users\talha.celik\Desktop\Talha\myerpv2-main\parameters\migrations\0003_auto_20211229_1054.py
# Compiled at: 2021-12-29 10:54:57
# Size of source mod 2**32: 7313 bytes
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
     ('parameters', '0002_pathtypemodel_icon_code')]
    operations = [
     migrations.AlterField(model_name='apptypemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='carclassmodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='cardtypemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='carfueltypemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='cartypemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='carusagemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='changepurposemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='citymodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='clothestypemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='continentmodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='corporationtypemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='countrymodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='emailtypemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='eventtypemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='financialcategorymodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='functiontypemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='gendermodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='genremodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='marketmodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='mediatypemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='operationtypemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='pathtypemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='periodmodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='phonetypemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='relationtypemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='repetitivetypemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='schooltypemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='seriesdownloadmodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='seriesstatemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='seriestypemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='townmodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
     migrations.AlterField(model_name='transactiontypemodel',
       name='id',
       field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'))]