# Generated by Django 3.1.4 on 2022-02-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_auto_20220225_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Uygulama Tipi',
                'db_table': 'parameters_apptype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PathTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kodu')),
                ('icon_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sidebar İcon Kodu')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Güzergah Tipi',
                'db_table': 'parameters_pathtype',
                'ordering': ['name'],
            },
        ),
    ]
