# uncompyle6 version 3.8.0
# Python bytecode 3.8.0 (3413)
# Decompiled from: Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
# Embedded file name: C:\Users\talha.celik\Desktop\Talha\myerpv2-main\parameters\migrations\0004_auto_20211230_1133.py
# Compiled at: 2021-12-30 11:33:56
# Size of source mod 2**32: 7084 bytes
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
     ('parameters', '0003_auto_20211229_1054')]
    operations = [
     migrations.AddField(model_name='apptypemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='carclassmodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='cardtypemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='carfueltypemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='cartypemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='carusagemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='changepurposemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='citymodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='clothestypemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='continentmodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='corporationtypemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='countrymodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='emailtypemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='eventtypemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='financialcategorymodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='functiontypemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='gendermodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='genremodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='marketmodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='mediatypemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='operationtypemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='pathtypemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='periodmodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='phonetypemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='relationtypemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='repetitivetypemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='schooltypemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='seriesdownloadmodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='seriesstatemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='seriestypemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='townmodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
     migrations.AddField(model_name='transactiontypemodel',
       name='desc',
       field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama'))]